name: infra
description: A hands-on learning experiment exploring backend, infrastructure, and API patterns with Rust, cloud-native tools, and generative AI (Google Gemini, Vertex AI).
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-python
